### ISSUE TITLE
Melpa?

### ISSUE THREAD

**Issue by SeanTAllen** [SeanTAllen/flycheck-pony#2]
Have you considered submitting flycheck-pony to melpa for slightly easier installation and discovery?

**Comment by rmloveland** [comment]
@SeanTAllen do you have any interest in taking over maintainership of this repo?  To be honest I've written hardly any Pony, I'm just an Emacs weirdo who was working through the tutorial and wanted my beloved Flycheck.  I'd be happy to give it to someone else who is more serious/committed/etc.

Alternatively, if you know/could recommend someone else that'd be fine too.

I agree it should be on MELPA.

**Comment by SeanTAllen** [comment]
@rmloveland yeah. i would, i'll fork it and you can shut this one down and I'll get on melpa etc.

**Comment by SeanTAllen** [comment]
@rmloveland actually, you want to try transfering the repo to me? happy to take it over. Thanks!

**Comment by SeanTAllen** [comment]
Done.
