### ISSUE TITLE
Checker errors due to bad interaction with Emacs lockfiles

### ISSUE THREAD

**Issue by ackalker** [SeanTAllen/flycheck-pony#3]
Editing a `.pony` file in Emacs 24.5.1 without saving it, I'm getting lots of:

```
Suspicious state from syntax checker pony: Checker pony returned non-zero exit code 255, but no errors from output: Building . -> /home/<user>/proj/pony/helloworld
/home/<user>/proj/pony/helloworld/.#main.pony: can't open file
/home/<user>/proj/pony/helloworld/.#main.pony: couldn't open file /home/<user>/proj/pony/helloworld/.#main.pony

Checker definition probably flawed.
```
The `.#main.pony` file appears to be a (broken) symlink which Emacs uses as a lockfile to avoid editing collisions.
A temporary workaround (until either an Emacs update handles these files differently or ponyc learns to ignore them) is to add
```elisp
(setq create-lockfiles nil)
```
in your `~/.emacs` file. See http://stackoverflow.com/q/5738170/588561 for more details.

**Comment by SeanTAllen** [comment]
Added to README.

**Comment by ackalker** [comment]
Thanks :)
