### ISSUE TITLE
Why `-rexpr` and not `-rfinal`?

### ISSUE THREAD

**Issue by rocha** [SeanTAllen/flycheck-pony#6]
Using `ponyc -rexpr` leaves exceptions/error checking out. For example the following code (taken from the tutorial) does not compile, but it passes checking with `-rexpr`.

```
actor Main
  new create(env: Env) =>
    let iterator = ["Bob"; "Fred"; "Sarah"].values()
    while iterator.has_next() do
      let name = iterator.next()?
      env.out.print(name)
    end
```

**Comment by SeanTAllen** [comment]
Thanks @rocha. This change is in the new version 0.2.2
